version: '2'

### Change the `project` with your own project name ###
services:
    application:
        container_name: project_application
        image: debian
        volumes:
            - ./:/home/app
    workspace:
        container_name: project_workspace
        restart: always
        image: framgia/rails-workspace
        volumes_from:
            - application
            - logs
        tty: true
    data:
        container_name: project_data
        image: debian
        volumes:
            - ./data/mysql:/var/lib/mysql
            - /private/var/lib/project_data:/data
            - /private/var/lib/project_logs/nginx:/var/log/nginx
    logs:
        container_name: project_logs
        image: debian
        volumes:
            - ./log/nginx:/var/log/nginx
    mysql:
        container_name: project_mysql
        restart: always
        image: mysql
        volumes_from:
            - data
            - logs
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: cucumber_rails5_development
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root